-- ============================================================
-- Migration 002 – Muscle-group / category tags for exercises
-- Run these statements in the Supabase SQL editor.
-- Adds a reusable tag vocabulary and a many-to-many join to
-- exercises so an exercise can carry multiple tags
-- (e.g. Barbell Row → compound, back, lats, lower back, biceps).
-- ============================================================

-- ------------------------------------------------------------
-- tags
-- Reusable muscle-group / category labels. Admin-managed,
-- readable by all authenticated users.
-- ------------------------------------------------------------
create table if not exists tags (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

alter table tags enable row level security;

create policy "Anyone can read tags"
  on tags for select using (auth.role() = 'authenticated');

create policy "Admins can insert tags"
  on tags for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can update tags"
  on tags for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can delete tags"
  on tags for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ------------------------------------------------------------
-- exercise_tags
-- Many-to-many join between exercises and tags.
-- ------------------------------------------------------------
create table if not exists exercise_tags (
  exercise_id bigint not null references exercises (id) on delete cascade,
  tag_id      bigint not null references tags (id) on delete cascade,
  primary key (exercise_id, tag_id)
);

alter table exercise_tags enable row level security;

create policy "Anyone can read exercise_tags"
  on exercise_tags for select using (auth.role() = 'authenticated');

create policy "Admins can insert exercise_tags"
  on exercise_tags for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can delete exercise_tags"
  on exercise_tags for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ------------------------------------------------------------
-- Seed a starter set of common tags.
-- ------------------------------------------------------------
insert into tags (name) values
  ('compound'), ('isolation'),
  ('chest'), ('back'), ('lats'), ('lower back'), ('shoulders'),
  ('biceps'), ('triceps'), ('forearms'),
  ('quads'), ('hamstrings'), ('glutes'), ('calves'),
  ('core'), ('abs'), ('cardio'), ('legs'), ('upper body'), ('full body')
on conflict (name) do nothing;
