-- ============================================================
-- Migration 005 – Workout templates (fase 5)
-- Run in the Supabase SQL editor after migration_004.
-- ============================================================

create table if not exists workout_templates (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  name       text not null,
  created_at timestamptz not null default now()
);

alter table workout_templates enable row level security;

create policy "Users can read own templates"
  on workout_templates for select using (auth.uid() = user_id);

create policy "Users can insert own templates"
  on workout_templates for insert with check (auth.uid() = user_id);

create policy "Users can update own templates"
  on workout_templates for update using (auth.uid() = user_id);

create policy "Users can delete own templates"
  on workout_templates for delete using (auth.uid() = user_id);

create table if not exists template_exercises (
  id          bigint generated by default as identity primary key,
  template_id bigint not null references workout_templates (id) on delete cascade,
  exercise_id bigint not null references exercises (id) on delete cascade,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

alter table template_exercises enable row level security;

create policy "Users can read own template_exercises"
  on template_exercises for select
  using (exists (select 1 from workout_templates t where t.id = template_id and t.user_id = auth.uid()));

create policy "Users can insert own template_exercises"
  on template_exercises for insert
  with check (exists (select 1 from workout_templates t where t.id = template_id and t.user_id = auth.uid()));

create policy "Users can delete own template_exercises"
  on template_exercises for delete
  using (exists (select 1 from workout_templates t where t.id = template_id and t.user_id = auth.uid()));

create policy "Users can update own template_exercises"
  on template_exercises for update
  using (exists (select 1 from workout_templates t where t.id = template_id and t.user_id = auth.uid()));

-- Track which template a workout was started from (nullable; set null if template deleted)
alter table workouts add column if not exists template_id bigint references workout_templates (id) on delete set null;
