-- ============================================================
-- Migration 012 – Private activity newsboard
-- Run in the Supabase SQL editor after migration_011.
-- ============================================================

alter table profiles
  add column if not exists nickname text;

create table if not exists boards (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_by uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists board_members (
  board_id  bigint not null references boards (id) on delete cascade,
  user_id   uuid not null references auth.users (id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (board_id, user_id)
);

create table if not exists activity_events (
  id             bigint generated by default as identity primary key,
  board_id       bigint not null references boards (id) on delete cascade,
  actor_user_id  uuid not null references auth.users (id) on delete cascade,
  actor_nickname text not null,
  event_type     text not null check (event_type in ('workout_completed', 'weight_weekly')),
  workout_id     bigint references workouts (id) on delete cascade,
  weight_id      bigint references "Weight" (id) on delete set null,
  payload        jsonb not null default '{}'::jsonb,
  occurred_at    timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

create index if not exists activity_events_board_occurred_idx
  on activity_events (board_id, occurred_at desc);

create unique index if not exists activity_events_one_workout_per_board
  on activity_events (board_id, workout_id)
  where workout_id is not null;

create unique index if not exists activity_events_one_weight_per_board
  on activity_events (board_id, weight_id)
  where weight_id is not null;

alter table boards enable row level security;
alter table board_members enable row level security;
alter table activity_events enable row level security;

create policy "Members can read their boards"
  on boards for select
  using (
    exists (
      select 1
      from board_members
      where board_members.board_id = boards.id
        and board_members.user_id = auth.uid()
    )
  );

create policy "Members can read their memberships"
  on board_members for select
  using (user_id = auth.uid());

create policy "Members can read board activity"
  on activity_events for select
  using (
    exists (
      select 1
      from board_members
      where board_members.board_id = activity_events.board_id
        and board_members.user_id = auth.uid()
    )
  );

-- Called by the app after its existing workout-stat calculation. The function
-- resolves identity and display data itself, so clients cannot post as a peer.
create or replace function public.publish_workout_activity(
  p_workout_id bigint,
  p_pr_count integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_nickname text;
  v_workout_name text;
  v_saved_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select
    coalesce(nullif(trim(w.name), ''), nullif(trim(t.name), ''), 'workout'),
    coalesce(w.saved_at, w.created_at)
  into v_workout_name, v_saved_at
  from workouts w
  left join workout_templates t on t.id = w.template_id
  where w.id = p_workout_id
    and w.user_id = v_user_id
    and w.status = 'saved';

  if not found then
    raise exception 'Saved workout not found';
  end if;

  select coalesce(nullif(trim(nickname), ''), 'Sportmaat')
  into v_nickname
  from profiles
  where id = v_user_id;

  insert into activity_events (
    board_id,
    actor_user_id,
    actor_nickname,
    event_type,
    workout_id,
    payload,
    occurred_at
  )
  select
    bm.board_id,
    v_user_id,
    v_nickname,
    'workout_completed',
    p_workout_id,
    jsonb_build_object(
      'workout_name', v_workout_name,
      'pr_count', greatest(coalesce(p_pr_count, 0), 0),
      'variant', floor(random() * 10)::integer
    ),
    v_saved_at
  from board_members bm
  where bm.user_id = v_user_id
  on conflict (board_id, workout_id) where workout_id is not null
  do update set
    actor_nickname = excluded.actor_nickname,
    payload = jsonb_set(
      jsonb_set(
        activity_events.payload,
        '{workout_name}',
        excluded.payload -> 'workout_name'
      ),
      '{pr_count}',
      excluded.payload -> 'pr_count'
    );
end;
$$;

revoke all on function public.publish_workout_activity(bigint, integer) from public;
grant execute on function public.publish_workout_activity(bigint, integer) to authenticated;

-- A weekly weight event is emitted only when a reference measurement exists
-- between five and nine days earlier. Updates/deletes intentionally stay quiet.
create or replace function public.emit_weekly_weight_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reference_weight real;
  v_delta real;
  v_category text;
  v_nickname text;
begin
  select old_weight.weight
  into v_reference_weight
  from "Weight" old_weight
  where old_weight.user_id = new.user_id
    and old_weight.id <> new.id
    and old_weight.date between (new.date - 9) and (new.date - 5)
  order by abs((new.date - old_weight.date) - 7), old_weight.date desc, old_weight.created_at desc
  limit 1;

  if v_reference_weight is null then
    return new;
  end if;

  v_delta := new.weight - v_reference_weight;
  v_category := case
    when v_delta < -0.2 then 'loss'
    when v_delta > 0.2 then 'gain'
    else 'stable'
  end;

  select coalesce(nullif(trim(nickname), ''), 'Sportmaat')
  into v_nickname
  from profiles
  where id = new.user_id;

  insert into activity_events (
    board_id,
    actor_user_id,
    actor_nickname,
    event_type,
    weight_id,
    payload,
    occurred_at
  )
  select
    bm.board_id,
    new.user_id,
    v_nickname,
    'weight_weekly',
    new.id,
    jsonb_build_object(
      'category', v_category,
      'delta_kg', round(v_delta::numeric, 1),
      'variant', floor(random() * 10)::integer
    ),
    new.created_at
  from board_members bm
  where bm.user_id = new.user_id
  on conflict (board_id, weight_id) where weight_id is not null
  do nothing;

  return new;
end;
$$;

drop trigger if exists on_weight_insert_emit_weekly_activity on "Weight";
create trigger on_weight_insert_emit_weekly_activity
  after insert on "Weight"
  for each row execute function public.emit_weekly_weight_activity();
