-- ============================================================
-- Fitness App – Supabase schema
-- Run these statements in the Supabase SQL editor.
-- ============================================================

-- ------------------------------------------------------------
-- profiles
-- One row per auth user; created via trigger on auth.users.
-- ------------------------------------------------------------
create table if not exists profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  is_admin   boolean not null default false,
  nickname   text,
  goals      text,
  notes      text,
  llm_prompt text,
  created_at timestamptz not null default now()
);

-- Auto-create a profile row whenever a new user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table profiles enable row level security;

create policy "Users can read own profile"
  on profiles for select using (auth.uid() = id);

create policy "Users can update own profile"
  on profiles for update using (auth.uid() = id);

-- ------------------------------------------------------------
-- exercises
-- Admin-managed catalog of exercises.
-- type = 'strength'   → sets tracked with weight_kg + reps
-- type = 'endurance'  → sets tracked with duration_seconds + distance_km
-- ------------------------------------------------------------
create table if not exists exercises (
  id         bigint generated by default as identity primary key,
  name       text not null,
  type       text not null check (type in ('strength', 'endurance')),
  notes      text,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now()
);

alter table exercises enable row level security;

-- Everyone can read exercises
create policy "Anyone can read exercises"
  on exercises for select using (auth.role() = 'authenticated');

-- Only admins can create/update/delete exercises
create policy "Admins can insert exercises"
  on exercises for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can update exercises"
  on exercises for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can delete exercises"
  on exercises for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ------------------------------------------------------------
-- workout_templates
-- ------------------------------------------------------------
create table if not exists workout_templates (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  name       text not null,
  created_at timestamptz not null default now()
);

alter table workout_templates enable row level security;

create policy "Users can read own templates"
  on workout_templates for select using (auth.uid() = user_id);
create policy "Users can insert own templates"
  on workout_templates for insert with check (auth.uid() = user_id);
create policy "Users can update own templates"
  on workout_templates for update using (auth.uid() = user_id);
create policy "Users can delete own templates"
  on workout_templates for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- workouts
-- ------------------------------------------------------------
create table if not exists workouts (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  date       date not null default current_date,
  name       text,
  notes      text,
  template_id bigint references workout_templates (id) on delete set null,
  status     text not null default 'active' check (status in ('active', 'saved')),
  created_at timestamptz not null default now(),
  saved_at   timestamptz
);

create unique index if not exists one_active_workout_per_user
  on workouts (user_id)
  where status = 'active';

alter table workouts enable row level security;

create policy "Users can read own workouts"
  on workouts for select using (auth.uid() = user_id);

create policy "Users can insert own workouts"
  on workouts for insert with check (auth.uid() = user_id);

create policy "Users can update own workouts"
  on workouts for update using (auth.uid() = user_id);

create policy "Users can delete own workouts"
  on workouts for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- workout_exercises
-- Join between a workout session and an exercise from the catalog.
-- sort_order determines display order within a workout.
-- ------------------------------------------------------------
create table if not exists workout_exercises (
  id          bigint generated by default as identity primary key,
  workout_id  bigint not null references workouts (id) on delete cascade,
  exercise_id bigint not null references exercises (id) on delete cascade,
  sort_order  int not null default 0,
  notes       text,
  pain_scale  int check (pain_scale >= 1 and pain_scale <= 10),
  created_at  timestamptz not null default now()
);

alter table workout_exercises enable row level security;

-- Access is granted via workouts ownership
create policy "Users can read own workout_exercises"
  on workout_exercises for select
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can insert own workout_exercises"
  on workout_exercises for insert
  with check (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can update own workout_exercises"
  on workout_exercises for update
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can delete own workout_exercises"
  on workout_exercises for delete
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

-- ------------------------------------------------------------
-- Weight
-- Body weight log entries per user.
-- ------------------------------------------------------------
create table if not exists "Weight" (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  weight     real not null,
  is_kg      boolean not null default true,
  date       date not null default current_date,
  created_at timestamptz not null default now()
);

alter table "Weight" enable row level security;

create policy "Users can read own weights"
  on "Weight" for select using (auth.uid() = user_id);

create policy "Users can insert own weights"
  on "Weight" for insert with check (auth.uid() = user_id);

create policy "Users can update own weights"
  on "Weight" for update using (auth.uid() = user_id);

create policy "Users can delete own weights"
  on "Weight" for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- exercise_sets
-- Individual sets within a workout_exercise entry.
-- Strength fields: weight_kg, reps
-- Endurance fields: duration_seconds, distance_km
-- ------------------------------------------------------------
create table if not exists exercise_sets (
  id                  bigint generated by default as identity primary key,
  workout_exercise_id bigint not null references workout_exercises (id) on delete cascade,
  set_number          int not null default 1,
  weight_kg           real,
  reps                int,
  duration_seconds    int,
  distance_km         real,
  created_at          timestamptz not null default now()
);

alter table exercise_sets enable row level security;

-- Access is granted transitively via workouts ownership
create policy "Users can read own exercise_sets"
  on exercise_sets for select
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can insert own exercise_sets"
  on exercise_sets for insert
  with check (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can update own exercise_sets"
  on exercise_sets for update
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can delete own exercise_sets"
  on exercise_sets for delete
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create index if not exists workout_exercises_exercise_created_idx
  on workout_exercises (exercise_id, created_at desc);

create index if not exists exercise_sets_we_set_number_idx
  on exercise_sets (workout_exercise_id, set_number desc);

create index if not exists exercise_sets_we_weight_idx
  on exercise_sets (workout_exercise_id, weight_kg desc)
  where weight_kg is not null;

-- ------------------------------------------------------------
-- Private activity newsboard (migration_012)
-- ------------------------------------------------------------
create table if not exists boards (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  created_by uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists board_members (
  board_id  bigint not null references boards (id) on delete cascade,
  user_id   uuid not null references auth.users (id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (board_id, user_id)
);

create table if not exists activity_events (
  id             bigint generated by default as identity primary key,
  board_id       bigint not null references boards (id) on delete cascade,
  actor_user_id  uuid not null references auth.users (id) on delete cascade,
  actor_nickname text not null,
  event_type     text not null check (event_type in ('workout_completed', 'weight_weekly')),
  workout_id     bigint references workouts (id) on delete cascade,
  weight_id      bigint references "Weight" (id) on delete set null,
  payload        jsonb not null default '{}'::jsonb,
  occurred_at    timestamptz not null default now(),
  created_at     timestamptz not null default now()
);

create index if not exists activity_events_board_occurred_idx
  on activity_events (board_id, occurred_at desc);
create unique index if not exists activity_events_one_workout_per_board
  on activity_events (board_id, workout_id) where workout_id is not null;
create unique index if not exists activity_events_one_weight_per_board
  on activity_events (board_id, weight_id) where weight_id is not null;

alter table boards enable row level security;
alter table board_members enable row level security;
alter table activity_events enable row level security;

create policy "Members can read their boards"
  on boards for select
  using (exists (
    select 1 from board_members
    where board_members.board_id = boards.id
      and board_members.user_id = auth.uid()
  ));

create policy "Members can read their memberships"
  on board_members for select using (user_id = auth.uid());

create policy "Members can read board activity"
  on activity_events for select
  using (exists (
    select 1 from board_members
    where board_members.board_id = activity_events.board_id
      and board_members.user_id = auth.uid()
  ));

create or replace function public.publish_workout_activity(
  p_workout_id bigint,
  p_pr_count integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_nickname text;
  v_workout_name text;
  v_saved_at timestamptz;
begin
  if v_user_id is null then raise exception 'Not authenticated'; end if;

  select
    coalesce(nullif(trim(w.name), ''), nullif(trim(t.name), ''), 'workout'),
    coalesce(w.saved_at, w.created_at)
  into v_workout_name, v_saved_at
  from workouts w
  left join workout_templates t on t.id = w.template_id
  where w.id = p_workout_id and w.user_id = v_user_id and w.status = 'saved';

  if not found then raise exception 'Saved workout not found'; end if;

  select coalesce(nullif(trim(nickname), ''), 'Sportmaat')
  into v_nickname from profiles where id = v_user_id;

  insert into activity_events (
    board_id, actor_user_id, actor_nickname, event_type,
    workout_id, payload, occurred_at
  )
  select
    bm.board_id, v_user_id, v_nickname, 'workout_completed',
    p_workout_id,
    jsonb_build_object(
      'workout_name', v_workout_name,
      'pr_count', greatest(coalesce(p_pr_count, 0), 0),
      'variant', floor(random() * 10)::integer
    ),
    v_saved_at
  from board_members bm
  where bm.user_id = v_user_id
  on conflict (board_id, workout_id) where workout_id is not null
  do update set
    actor_nickname = excluded.actor_nickname,
    payload = jsonb_set(
      jsonb_set(activity_events.payload, '{workout_name}', excluded.payload -> 'workout_name'),
      '{pr_count}',
      excluded.payload -> 'pr_count'
    );
end;
$$;

revoke all on function public.publish_workout_activity(bigint, integer) from public;
grant execute on function public.publish_workout_activity(bigint, integer) to authenticated;

create or replace function public.emit_weekly_weight_activity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reference_weight real;
  v_delta real;
  v_category text;
  v_nickname text;
begin
  select old_weight.weight
  into v_reference_weight
  from "Weight" old_weight
  where old_weight.user_id = new.user_id
    and old_weight.id <> new.id
    and old_weight.date between (new.date - 9) and (new.date - 5)
  order by abs((new.date - old_weight.date) - 7), old_weight.date desc, old_weight.created_at desc
  limit 1;

  if v_reference_weight is null then return new; end if;

  v_delta := new.weight - v_reference_weight;
  v_category := case
    when v_delta < -0.2 then 'loss'
    when v_delta > 0.2 then 'gain'
    else 'stable'
  end;

  select coalesce(nullif(trim(nickname), ''), 'Sportmaat')
  into v_nickname from profiles where id = new.user_id;

  insert into activity_events (
    board_id, actor_user_id, actor_nickname, event_type,
    weight_id, payload, occurred_at
  )
  select
    bm.board_id, new.user_id, v_nickname, 'weight_weekly',
    new.id,
    jsonb_build_object(
      'category', v_category,
      'delta_kg', round(v_delta::numeric, 1),
      'variant', floor(random() * 10)::integer
    ),
    new.created_at
  from board_members bm
  where bm.user_id = new.user_id
  on conflict (board_id, weight_id) where weight_id is not null do nothing;

  return new;
end;
$$;

drop trigger if exists on_weight_insert_emit_weekly_activity on "Weight";
create trigger on_weight_insert_emit_weekly_activity
  after insert on "Weight"
  for each row execute function public.emit_weekly_weight_activity();

-- ------------------------------------------------------------
-- Session references (migration_013)
-- One round-trip: all-time heaviest set + last 2 sets of the previous session.
-- ------------------------------------------------------------
create or replace function public.exercise_session_refs(
  p_exercise_ids bigint[],
  p_exclude_workout_id bigint
)
returns table (
  exercise_id bigint,
  best_set jsonb,
  last_sets jsonb
)
language sql
stable
security invoker
set search_path = public
as $$
  with best as (
    select distinct on (we.exercise_id)
      we.exercise_id,
      jsonb_build_object(
        'id', es.id,
        'workout_exercise_id', es.workout_exercise_id,
        'set_number', es.set_number,
        'weight_kg', es.weight_kg,
        'reps', es.reps,
        'duration_seconds', es.duration_seconds,
        'distance_km', es.distance_km,
        'created_at', es.created_at
      ) as best_set
    from exercise_sets es
    join workout_exercises we on we.id = es.workout_exercise_id
    join workouts w on w.id = we.workout_id
    where we.exercise_id = any (p_exercise_ids)
      and we.workout_id is distinct from p_exclude_workout_id
      and w.status = 'saved'
      and es.weight_kg is not null
    order by we.exercise_id, es.weight_kg desc, es.reps desc nulls last, es.id desc
  ),
  latest_we as (
    select distinct on (we.exercise_id)
      we.exercise_id,
      we.id as workout_exercise_id
    from workout_exercises we
    where we.exercise_id = any (p_exercise_ids)
      and we.workout_id is distinct from p_exclude_workout_id
    order by we.exercise_id, we.created_at desc
  ),
  last as (
    select
      latest_we.exercise_id,
      coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', es.id,
            'workout_exercise_id', es.workout_exercise_id,
            'set_number', es.set_number,
            'weight_kg', es.weight_kg,
            'reps', es.reps,
            'duration_seconds', es.duration_seconds,
            'distance_km', es.distance_km,
            'created_at', es.created_at
          )
          order by es.set_number
        ) filter (where es.id is not null),
        '[]'::jsonb
      ) as last_sets
    from latest_we
    left join lateral (
      select
        es.id,
        es.workout_exercise_id,
        es.set_number,
        es.weight_kg,
        es.reps,
        es.duration_seconds,
        es.distance_km,
        es.created_at
      from exercise_sets es
      where es.workout_exercise_id = latest_we.workout_exercise_id
      order by es.set_number desc
      limit 2
    ) es on true
    group by latest_we.exercise_id
  )
  select
    ids.exercise_id,
    b.best_set,
    coalesce(l.last_sets, '[]'::jsonb) as last_sets
  from (select distinct unnest(p_exercise_ids) as exercise_id) ids
  left join best b on b.exercise_id = ids.exercise_id
  left join last l on l.exercise_id = ids.exercise_id
$$;

revoke all on function public.exercise_session_refs(bigint[], bigint) from public;
grant execute on function public.exercise_session_refs(bigint[], bigint) to authenticated;
