-- ============================================================
-- Fitness App – Supabase schema
-- Run these statements in the Supabase SQL editor.
-- ============================================================

-- ------------------------------------------------------------
-- profiles
-- One row per auth user; created via trigger on auth.users.
-- ------------------------------------------------------------
create table if not exists profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  is_admin   boolean not null default false,
  goals      text,
  notes      text,
  llm_prompt text,
  created_at timestamptz not null default now()
);

-- Auto-create a profile row whenever a new user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table profiles enable row level security;

create policy "Users can read own profile"
  on profiles for select using (auth.uid() = id);

create policy "Users can update own profile"
  on profiles for update using (auth.uid() = id);

-- ------------------------------------------------------------
-- exercises
-- Admin-managed catalog of exercises.
-- type = 'strength'   → sets tracked with weight_kg + reps
-- type = 'endurance'  → sets tracked with duration_seconds + distance_km
-- ------------------------------------------------------------
create table if not exists exercises (
  id         bigint generated by default as identity primary key,
  name       text not null,
  type       text not null check (type in ('strength', 'endurance')),
  notes      text,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now()
);

alter table exercises enable row level security;

-- Everyone can read exercises
create policy "Anyone can read exercises"
  on exercises for select using (auth.role() = 'authenticated');

-- Only admins can create/update/delete exercises
create policy "Admins can insert exercises"
  on exercises for insert
  with check (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can update exercises"
  on exercises for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Admins can delete exercises"
  on exercises for delete
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ------------------------------------------------------------
-- workouts
-- One row per (user, date). Created automatically when a user
-- starts adding exercises on a given day.
-- ------------------------------------------------------------
create table if not exists workouts (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  date       date not null default current_date,
  notes      text,
  created_at timestamptz not null default now(),
  unique (user_id, date)
);

alter table workouts enable row level security;

create policy "Users can read own workouts"
  on workouts for select using (auth.uid() = user_id);

create policy "Users can insert own workouts"
  on workouts for insert with check (auth.uid() = user_id);

create policy "Users can update own workouts"
  on workouts for update using (auth.uid() = user_id);

create policy "Users can delete own workouts"
  on workouts for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- workout_exercises
-- Join between a workout session and an exercise from the catalog.
-- sort_order determines display order within a workout.
-- ------------------------------------------------------------
create table if not exists workout_exercises (
  id          bigint generated by default as identity primary key,
  workout_id  bigint not null references workouts (id) on delete cascade,
  exercise_id bigint not null references exercises (id) on delete cascade,
  sort_order  int not null default 0,
  notes       text,
  pain_scale  int check (pain_scale >= 1 and pain_scale <= 10),
  created_at  timestamptz not null default now()
);

alter table workout_exercises enable row level security;

-- Access is granted via workouts ownership
create policy "Users can read own workout_exercises"
  on workout_exercises for select
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can insert own workout_exercises"
  on workout_exercises for insert
  with check (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can update own workout_exercises"
  on workout_exercises for update
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

create policy "Users can delete own workout_exercises"
  on workout_exercises for delete
  using (exists (select 1 from workouts w where w.id = workout_id and w.user_id = auth.uid()));

-- ------------------------------------------------------------
-- Weight
-- Body weight log entries per user.
-- ------------------------------------------------------------
create table if not exists "Weight" (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  weight     real not null,
  is_kg      boolean not null default true,
  date       date not null default current_date,
  created_at timestamptz not null default now()
);

alter table "Weight" enable row level security;

create policy "Users can read own weights"
  on "Weight" for select using (auth.uid() = user_id);

create policy "Users can insert own weights"
  on "Weight" for insert with check (auth.uid() = user_id);

create policy "Users can update own weights"
  on "Weight" for update using (auth.uid() = user_id);

create policy "Users can delete own weights"
  on "Weight" for delete using (auth.uid() = user_id);

-- ------------------------------------------------------------
-- exercise_sets
-- Individual sets within a workout_exercise entry.
-- Strength fields: weight_kg, reps
-- Endurance fields: duration_seconds, distance_km
-- ------------------------------------------------------------
create table if not exists exercise_sets (
  id                  bigint generated by default as identity primary key,
  workout_exercise_id bigint not null references workout_exercises (id) on delete cascade,
  set_number          int not null default 1,
  weight_kg           real,
  reps                int,
  duration_seconds    int,
  distance_km         real,
  created_at          timestamptz not null default now()
);

alter table exercise_sets enable row level security;

-- Access is granted transitively via workouts ownership
create policy "Users can read own exercise_sets"
  on exercise_sets for select
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can insert own exercise_sets"
  on exercise_sets for insert
  with check (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can update own exercise_sets"
  on exercise_sets for update
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));

create policy "Users can delete own exercise_sets"
  on exercise_sets for delete
  using (exists (
    select 1 from workout_exercises we
    join workouts w on w.id = we.workout_id
    where we.id = workout_exercise_id and w.user_id = auth.uid()
  ));
